### ISSUE TITLE
Pitch to Director in engaging CFOB's Investment Advisory Group

### ISSUE THREAD

**Issue by remyb2canada** [sara-sabr/ITStrategy#1012]
purpose: present to Director a case for establishing relationship with the CFOB's Investment Advisory Group

This links to:
- GCDevExchange
- Target IT Solution Delivery Model
- Risk Management of technology (IITB Risk Register and IITB's Compliance Unit)

Reference Materials:
- email from Rachel/Remy on 2020-05-22
- [investment plan](https://dialogue.hrdc-drhc.net/grp/IPPST/Investment%20Plan/Forms/AllItems.aspx?RootFolder=%2Fgrp%2FIPPST%2FInvestment%20Plan%2F2018%2D2019%20to%202022%2D2023%2FInvestment%20Plan%20Documents)
- [Investment Portfolio Management Sharepoint site](https://dialogue.hrdc-drhc.net/grp/IPPST/SitePages/Landing%20Page.aspx)

**Comment by smellems** [comment]
Draft email for PMO to send to CFOB

**Comment by gcharest** [comment]
Need to brief CIO on approach (PPRC/DGCom) before actual engagement with committees outside IITB since he may be required to present it himself but we can reach into working level and unofficial contacts for pre-brief of the approach.

**Comment by gcharest** [comment]
Linked to #1146

**Comment by gcharest** [comment]
Action Items from discussion with Strategy Director:

- Book 1h with Strategy Director, ExDir and a/DG after his return from vacation (also need presenters available), might be first of September
- Book PPOC/PPRC for September (August: almost only actings at committees; Dir. most likely to present at PPRC while team at PPOC - need to confirm)
- Book OCMC/ARC/EARB as early as convenient (Team presents)
- Adapt presentation content for new purpose: need to clearly outline the SDM as most people in those committees may not have read the documentation (current version of the deck is tailored for folks who most likely read it already or for the purpose of reading it as an action item; this time, we're explaining the Strategy and the impact on IITB/ESDC)
- Start engagement with outside groups but NOT the committees since they are almost at ADM level: Will need CIO to be briefed and in agreement with approach first
- Dir. to present at DG Com, most likely will be a/DG or CIO themselves presenting at Audit and CFOB committees since audience mostly is ADM level. Engagement will need to be properly documented to support the desired outcome message for those specific groups.

**Comment by gcharest** [comment]
@smellems @myp192 @gabrielcossette We'll need to sync on the actions so that we don't duplicate the requests. Thanks!

**Comment by jaysonmc** [comment]
Based on @gcharest's comment above, this is in progress, given we've booked meetings with PPOC and PPRC and OCMC, so we've started this?

It's an epic, so should we close and just break down into separate issues?

**Comment by remyb2canada** [comment]
closing this issue as we've already engaged with CFOB for the micro-acquisition.

Will create a new one relating to the business case for agile gov framework
