### ISSUE TITLE
Complete A11y review of IT Strategy site using CDS A11y Review Process

### ISSUE THREAD

**Issue by jaysonmc** [sara-sabr/ITStrategy#1023]
Link to the CDS accessibility handbook: https://digital.canada.ca/a11y/
Also this handbook links to the 18F Accessibility checklist: https://accessibility.18f.gov/checklist/
This part of the CDS accessibility handbook is very useful: https://digital.canada.ca/a11y/how-to-make-it-accessible/

**Comment by jaysonmc** [comment]
- Add link on website for people to be able to open accessibility issues on the site

**Comment by RachelMuston** [comment]
Link to the CDS accessibility handbook:  https://digital.canada.ca/a11y/
Also this handbook links to the 18F Accessibility checklist: https://accessibility.18f.gov/checklist/
This part of the CDS accessibility handbook is very useful: https://digital.canada.ca/a11y/how-to-make-it-accessible/

**Comment by RachelMuston** [comment]
Images to add descriptive text to:
Page: ESDC IT Strategy - logic model image
Page: Strategy-summary.html (strategy map image)
Page: Transition-to-partner.html (range of modeling by pace layering and bimodality)
Blog: Case-continuous-improvement-deeper-dive.html (2 images)

Change the image to a table so that it can be read by a screen reader
page: quarterly-delivery 

Still to review: 
Archives
PowerPoint presentations

**Comment by RachelMuston** [comment]
to make the ppts on the site accessible...we could follow the guidance from the IITB Showcase folks as follows:
1. Ensure the graphics have alternate text (right click on image, click on format picture, select 'alt text' and add a title and description for the image)
2. use the built in accessibility checker in ppt.  (click on File, click on 'Check for issues', select 'check accessibility'.  Review the inspection results and make the required changes.
