### ISSUE TITLE
Presentation to CIOEC - Nov 2nd

### ISSUE THREAD

**Issue by smellems** [sara-sabr/ITStrategy#1198]

**Comment by gcharest** [comment]
Presentation completed, lots of very good feedback from Executive Directors and CIO.

Endorsed direction taken with a caveat: need to realign with BDM so that there is a single departmental approach.

Notes: https://014gc.sharepoint.com/:w:/s/strategyBuildvsBuy/EbW4o5v5T6tHjCf4iYNClA0BoEUqsXITh8qTU_lC-nTpZw?e=nLiMyi
