### ISSUE TITLE
Help optimize Tech Arch bricks

### ISSUE THREAD

**Issue by gabrielcossette** [sara-sabr/ITStrategy#121]
What are there deliverables?
What are they working on? 
How could they automate their processes? 

- [ ] Meet with the Technical Architecture group
- [ ] Brief team

**Comment by remyb2canada** [comment]
Subject to talk to them:
- what are the benefits of standards to the dept?
- what should be standardized and what should not?
- bi-modal (some technology may be standardized, like large complex and expensive systems, but others not like development tools and stacks since they change too often; moving to micro-services may not have that much impact on skillsets and maintenance, etc.)

**Comment by gcharest** [comment]
Was there a meeting setup? Did we follow up on this? Will leave open but worth a review.
