### ISSUE TITLE
Setup Ottawa DevOps Days

### ISSUE THREAD

**Issue by gabrielcossette** [sara-sabr/ITStrategy#129]
https://gcdevopsleague.slack.com/messages/CK8QG4PL4/

1. Does the GoC count as one org, or would each department be a different org?
2. Find contacts from within GoC 

- [x] Contact DevOps days organizers
- [x] Contact Values and Ethics
- [x] Meet with Values and Ethics
- [x] Contact GitHub

**Comment by gcharest** [comment]
Will need to contact more external partners. GitHub are looking into their capacity to be co-organizers (they've been one in the past).
Part of the question here is that co-organizers are not necessarily sponsors: they are organizing and will be collecting money from both sponsors and attendees which is why this will be a GC DevOps league initiative rather than an ESDC one. I'd close the issue here.
