### ISSUE TITLE
Write deck to be used for buy-in

### ISSUE THREAD

**Issue by gabrielcossette** [sara-sabr/ITStrategy#1516]
Write draft Strategy for Sharing of software assessments, in the typical format.

**Comment by RachelMuston** [comment]
Modifying this issue slightly to align with the current plan - pilot initiative for a year (rather than a strategy).
The slide deck will cover - what the problem is,  pilot and timelines, roles and responsibilities.
The audience for the deck will first be the directors of the pillars, but then also used to socialize the initiative to senior mgmt in SABR, and then to communicate out (might need to be a slightly modified deck to communicate out).

**Comment by RachelMuston** [comment]
Deck to be used to discuss with the pillars drafted: https://014gc.sharepoint.com/:p:/r/sites/IITB-ITStrategy/Shared%20Documents/STRATEGIES%20AND%20INITIATIVES/Sharing%20Software%20Assessments/Sharing_software_assessment_artefacts_to_pillars.pptx?d=w9583a20fc9f3437b8b18bce35d124935&csf=1&web=1&e=dN1gNV
