### ISSUE TITLE
Define continuous learning avenues (Guidance)

### ISSUE THREAD

**Issue by remyb2canada** [sara-sabr/ITStrategy#578]
Ideation 

Propose continuous learning avenues as part of strategies (inspiration from The Unicorn Project, page 315):

- Dojo attendence (needs imementation of DTS idea)
- micro missions in another functional/business unit (e.g. dev in test, security in dev, Dev in ops)
- take part in service Canada staff training
- learn a new tech or tool
- participate in innovation Lab design sessions
- data science (partnership with the CDO)
- new coding paradigms and patterns (DevOps CoE, functional programming)

**Comment by smellems** [comment]
I was going to create a new Issue, but putting it here.

We need to add more Guidance on how to "learn" and "improve".  Also figure out how to present Guidance as there are a lot of ideas..

From @jaysonmc Adding language regarding contributions to open source projects as counting as time spent towards continuous improvement (Ex: increase accessibility of a solution that is used, or you feel could or should be used, by ESDC or GoC).

Also self directed learning
Courses on brilliant.org, or Coursera, or whatever else

**Comment by RachelMuston** [comment]
Been thinking about this since Jayson mentioned it yesterday....with our plan for comms to officially release/post the strategy somewhere official and I'm assuming outside of our reach, our ability to adjust the guidance that is embedded in the strategy is reduced. 

Could we make a minor revision to the strategy to make it clear that 'Learn' and 'Improve' actions are just some examples and then have a link to a separate more comprehensive guidance piece on our website? Also perhaps consider shortening the lists of examples of activities we have embedded in the strategy to reduce the risk of outdated content once the strategy is officially released?

So many thoughts about the guidance piece.....For the training side of things, we could also link to specific training resources developed by our learning team/digital academy or even ones that we've taken/books we've read to make it as easy as possible for folks to get started with learning (not waste time searching for learning materials).  Along those lines comms will likely recommend that we add links to the specific training activities we currently have in the strategy (Register for training events offered by ESDC (link) and CSPS (link), explore opportunities with CDO (link - assuming there is one), GCconnex (link) and GCcollab (link)?

Oh and also it would be cool to have in our guidance, learning activities broken down by how much learning time you have available (similar to medium blog posts).  E.g. I have 15 mins right now, what can I learn? click, learn, done.  :-)

**Comment by remyb2canada** [comment]
Reference to the [IITB Operational Staffing Plan 2018-2019](http://dialogue/grp/WM-Gde/Operational%20Staffing%20Plan/PMD%20OSP%20Library/2018-19_Operational_Staffing_Plan_IITB.docx) that can have interesting avenues already supported. E.g.:

> Collaborate with the business side of ESDC to exchange resources temporarily so as to learn and share knowledge in various areas e.g. finance, human resources (HR), business relationship management (BRM), project management, etc.;

**Comment by jaysonmc** [comment]
This is kind of in progress, no? Many of the comments Remy made have since been incorporated into the document. 

@remyb2canada 
Should we close this, or should it be moved to in progress if some of the items are still felt to be missing?

@RachelMuston 
This is a good comment, regarding once it is "published" then the internal 'official' version will be more static than the rest of our content. Unless of course, on whatever they publish, they can offer a link to our site to always be able to see the updated guidance (though I assume that is local will be the 'approved' version). 
As for linking to training, I think the approach thus far has been to reference our references page (https://sara-sabr.github.io/ITStrategy/references-en.html). We could add more links or specifics about GoC available training. Think that's a good idea.
