### ISSUE TITLE
Validate use of 2SVM cost center for Continuous improvment

### ISSUE THREAD

**Issue by smellems** [sara-sabr/ITStrategy#611]
A CATS code requires a cost centre.  The code create for us uses our cost centre, but the code is intended to be used by all IITB.

Will that be a problem?  Changing cost centre will require a new code.  Its better to change now than once people start using it

**Comment by RachelMuston** [comment]
From the CATS team:  "The way certain CATS code work is that anyone can use them within IITB. For the RUN codes ( codes starting with 1) , theses codes are tied to a cost Center only for non-salary costs. As for Salary , the employee’s forecasted Cost Center will take effect rather then the CATS code ‘s Cost Center. "

So it is ok for our code: 14644 to be used by anyone in IITB because the salary costs associated with folks using this code code will go to that employee's boss's cost centre and not Jayson's.
