### ISSUE TITLE
Tech analysis - what is needed to bring GCDevEx back online (also costs)

### ISSUE THREAD

**Issue by RachelMuston** [sara-sabr/ITStrategy#920]

**Comment by smellems** [comment]
### GCdevex
Contains changes done in 2017-2018 to add translations (French and English) and the WET-BOEW Canada theme.
Tracking of upstream branch stopped in 2018.
The current code does not work anymore because of outdated/incompatible software (Node, ..)
Merging BCdevex changes into GCdevex is 2008 commits, 1074 files.
https://github.com/canada-ca/devex/compare/master...BCDevExchange:master

#### Angular Translate
The angular-translate library is what was used to enable translation on the original GCdevex.
https://angular-translate.github.io/docs/#/guide/07_multi-language


### BCdevex (upstream)
The main codebase for the BC Developer exchange (Devex).
Major changes have been made to the code since changes were merged into GCdevex.
Merging GCdevex changes into BCdevex is a little less complicated (220 commits, 191 files)
https://github.com/BCDevExchange/devex/compare/master...canada-ca:master
There are many conflicts and files that were deleted/moved

Running the software in the way described in the README was not working because of an outdated Node version in the Dockerfile.
A Pull Request was submitted with a fix - https://github.com/BCDevExchange/devex/pull/624


Latest work on new version of GCdevex base on the latest BCdevex code
https://github.com/canada-ca/devex/tree/restart
